function ExportHiLo(d, template)
    if isstruct(d)
        doExportHiLo(d, template);
    elseif iscell(d)
        for i = 1:length(d)
            doExportHiLo(d{i}, template);
        end
    end       
end

function doExportHiLo(d, template)
    re = '(.*)\.csv';
    match = regexp(d.fname,re,'tokens');
    base_fname = char(match{1});
    fname1 = [char(match{1}) '.mat.csv'];
    fname2 = [char(match{1}) '.dgraph'];
    if ~isfield(d,'G')
        d.G = zeros(size(d.Vg));
    end
    csvwrite(fname1, [d.Vg d.phi_s d.Ec_Ef ...
                      d.Cqs d.Chf d.Chf_ideal d.Cs_qs d.Cs_hf d.Cs_ideal ...
                      d.G d.Qt d.Dit_hilo d.Dit_Cpsi]);
    template_fname = ['/Users/Dallas/Documents/DataGraph/' template '.dgraph'];
    system(['/usr/local/bin/dgraph ' fname1 ...
            ' -script '     template_fname ... 
            ' -output '     fname2 ...
            ' -v fname='    base_fname ...
            ' -v Cox='      num2str(d.Cox) ...
            ' -v Area='     num2str(d.area) ...
            ' -v T='        num2str(d.T) ...
            ' -v f='        num2str(d.f) ...
            ' -v Vfb='      num2str(d.Vfb) ...
            ' -v Cfb='      num2str(d.Cfb) ...
            ' -v Ecb_Ef='   num2str(d.Ecb_Ef) ...
            ' -v Cfb_ideal=' num2str(d.Cfb_ideal) ...
           ]);
    system(['rm -f ' fname1]);
end
